"""Target languages (ported from goobleTranslator)."""

LANGUAGES: list[str] = [
    "Amharic",
    "Arabic",
    "Bengali",
    "English",
    "French",
    "Fulani",
    "German",
    "Gujarati",
    "Hausa",
    "Hindi",
    "Igbo",
    "Japanese",
    "Javanese",
    "Kannada",
    "Korean",
    "Malay",
    "Malayalam",
    "Mandarin Chinese",
    "Marathi",
    "Polish",
    "Portuguese",
    "Punjabi",
    "Russian",
    "Shona",
    "Somali",
    "Spanish",
    "Swahili",
    "Tamil",
    "Telugu",
    "Tigrinya",
    "Turkish",
    "Urdu",
    "Vietnamese",
    "Wu Chinese",
    "Yoruba",
    "Zulu",
]
